version: '2'

services:
  web3-ai-auditor:
    build: ./app
    ports:
      - "7081:7081"
    env_file:
      - .env
    volumes:
      - ./app/models:/app/models
      - ./app/uploads:/app/uploads
    restart: unless-stopped