version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=AIzaSyCFFMCwHOJ4Ehib3nyJvjIVxTI2KkJLeYk
      # Add additional environment variables here as needed
